//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources.Validations.Arabic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ar_Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ar_Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.Validations.Arabic.Ar_Responses", typeof(Ar_Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فدان مطلوب.
        /// </summary>
        public static string AcreOrchards {
            get {
                return ResourceManager.GetString("AcreOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع النشاط مطلوب.
        /// </summary>
        public static string ActivityTypeFarms {
            get {
                return ResourceManager.GetString("ActivityTypeFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmActivityType is invalid.
        /// </summary>
        public static string ActivityTypeNotValid {
            get {
                return ResourceManager.GetString("ActivityTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2023.
        /// </summary>
        public static string ActivityTypeNumberOnly {
            get {
                return ResourceManager.GetString("ActivityTypeNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012.
        /// </summary>
        public static string ActivityTypeValidations {
            get {
                return ResourceManager.GetString("ActivityTypeValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2030.
        /// </summary>
        public static string AddressOrchards {
            get {
                return ResourceManager.GetString("AddressOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2047.
        /// </summary>
        public static string AddressShipmment {
            get {
                return ResourceManager.GetString("AddressShipmment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2008.
        /// </summary>
        public static string ApplicantAddress {
            get {
                return ResourceManager.GetString("ApplicantAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاميل مطلوب.
        /// </summary>
        public static string ApplicantEmail {
            get {
                return ResourceManager.GetString("ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى غير صحيح.
        /// </summary>
        public static string ApplicantEmailFormat {
            get {
                return ResourceManager.GetString("ApplicantEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2007.
        /// </summary>
        public static string ApplicantGovernorate {
            get {
                return ResourceManager.GetString("ApplicantGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Governorate Code  is Invalid.
        /// </summary>
        public static string ApplicantGovernorateCodeNotExist {
            get {
                return ResourceManager.GetString("ApplicantGovernorateCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2077.
        /// </summary>
        public static string ApplicantGovernorateNotValid {
            get {
                return ResourceManager.GetString("ApplicantGovernorateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2004.
        /// </summary>
        public static string ApplicantName {
            get {
                return ResourceManager.GetString("ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المساحة(متر مربع) مطلوب.
        /// </summary>
        public static string AreaFarms {
            get {
                return ResourceManager.GetString("AreaFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2062.
        /// </summary>
        public static string AttachmentCodeNotValid {
            get {
                return ResourceManager.GetString("AttachmentCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2043.
        /// </summary>
        public static string AttachmentCodeRequired {
            get {
                return ResourceManager.GetString("AttachmentCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2061.
        /// </summary>
        public static string AttachmentNameRequired {
            get {
                return ResourceManager.GetString("AttachmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2066.
        /// </summary>
        public static string AttachmentRequired {
            get {
                return ResourceManager.GetString("AttachmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachement is required.
        /// </summary>
        public static string attchmentsRequired {
            get {
                return ResourceManager.GetString("attchmentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة التوكيل.
        /// </summary>
        public static string AttorneyAttchments {
            get {
                return ResourceManager.GetString("AttorneyAttchments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاب التفويض.
        /// </summary>
        public static string Authorizationletter {
            get {
                return ResourceManager.GetString("Authorizationletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2086.
        /// </summary>
        public static string AuthorizationNumberNotValid {
            get {
                return ResourceManager.GetString("AuthorizationNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3026.
        /// </summary>
        public static string AuthoriztionDateTimeNotValid {
            get {
                return ResourceManager.GetString("AuthoriztionDateTimeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تنفيذ الطلب بنجاح.
        /// </summary>
        public static string CancelRequestMessage {
            get {
                return ResourceManager.GetString("CancelRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is required.
        /// </summary>
        public static string CharacterRequired {
            get {
                return ResourceManager.GetString("CharacterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2041.
        /// </summary>
        public static string charchternotValid {
            get {
                return ResourceManager.GetString("charchternotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charchter required.
        /// </summary>
        public static string charchterRequired {
            get {
                return ResourceManager.GetString("charchterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2029.
        /// </summary>
        public static string CityOrchards {
            get {
                return ResourceManager.GetString("CityOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2050.
        /// </summary>
        public static string CodeInvalidLookup {
            get {
                return ResourceManager.GetString("CodeInvalidLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود غير موجود.
        /// </summary>
        public static string CodeNotFound {
            get {
                return ResourceManager.GetString("CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرجو أدخال الكود.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2049.
        /// </summary>
        public static string CodeRequiredLookup {
            get {
                return ResourceManager.GetString("CodeRequiredLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2054.
        /// </summary>
        public static string CollectionFeesAmount {
            get {
                return ResourceManager.GetString("CollectionFeesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2057.
        /// </summary>
        public static string CollectionFeesAmountNotValid {
            get {
                return ResourceManager.GetString("CollectionFeesAmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2081.
        /// </summary>
        public static string CommercialRegistrationNotValid {
            get {
                return ResourceManager.GetString("CommercialRegistrationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013.
        /// </summary>
        public static string CommercialRegistrationNoValidations {
            get {
                return ResourceManager.GetString("CommercialRegistrationNoValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information  is required.
        /// </summary>
        public static string CompanyInfoRequired {
            get {
                return ResourceManager.GetString("CompanyInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2033.
        /// </summary>
        public static string ComplainedPartyIsRequired {
            get {
                return ResourceManager.GetString("ComplainedPartyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2035.
        /// </summary>
        public static string ComplaintSubjectIsRequired {
            get {
                return ResourceManager.GetString("ComplaintSubjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2036.
        /// </summary>
        public static string correlationIdRequired {
            get {
                return ResourceManager.GetString("correlationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2058.
        /// </summary>
        public static string CustomerAuthorizationAmountNotValid {
            get {
                return ResourceManager.GetString("CustomerAuthorizationAmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2052.
        /// </summary>
        public static string CustomerAuthorizationAmountRequired {
            get {
                return ResourceManager.GetString("CustomerAuthorizationAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data or Attachement is required.
        /// </summary>
        public static string DataorAttachementisrequired {
            get {
                return ResourceManager.GetString("DataorAttachementisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل تاريخ صحيح.
        /// </summary>
        public static string DateTimeFormatError {
            get {
                return ResourceManager.GetString("DateTimeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2060.
        /// </summary>
        public static string DeliveryMethodNotValid {
            get {
                return ResourceManager.GetString("DeliveryMethodNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2042.
        /// </summary>
        public static string DeliveryMethodRequired {
            get {
                return ResourceManager.GetString("DeliveryMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011.
        /// </summary>
        public static string DetailedAddressValidations {
            get {
                return ResourceManager.GetString("DetailedAddressValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2024.
        /// </summary>
        public static string EasternBorderOrchards {
            get {
                return ResourceManager.GetString("EasternBorderOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2076.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا أثناء  الحفظ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2091.
        /// </summary>
        public static string FarmAcreOrchardsNotValid {
            get {
                return ResourceManager.GetString("FarmAcreOrchardsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmActivityType is required.
        /// </summary>
        public static string FarmActivityTypeRequired {
            get {
                return ResourceManager.GetString("FarmActivityTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016.
        /// </summary>
        public static string FarmAddress {
            get {
                return ResourceManager.GetString("FarmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018.
        /// </summary>
        public static string FarmArea {
            get {
                return ResourceManager.GetString("FarmArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2089.
        /// </summary>
        public static string FarmBuildingIdNotValid {
            get {
                return ResourceManager.GetString("FarmBuildingIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2092.
        /// </summary>
        public static string FarmCaratOrchardsNotValid {
            get {
                return ResourceManager.GetString("FarmCaratOrchardsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.
        /// </summary>
        public static string FarmCity {
            get {
                return ResourceManager.GetString("FarmCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2088.
        /// </summary>
        public static string FarmGeographicalLocation {
            get {
                return ResourceManager.GetString("FarmGeographicalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014.
        /// </summary>
        public static string FarmGovernorate {
            get {
                return ResourceManager.GetString("FarmGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2097.
        /// </summary>
        public static string FarmGovernorateNotValid {
            get {
                return ResourceManager.GetString("FarmGovernorateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3023.
        /// </summary>
        public static string FarmGovernorateOrchaNotValid {
            get {
                return ResourceManager.GetString("FarmGovernorateOrchaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2090.
        /// </summary>
        public static string FarmIdInvalid {
            get {
                return ResourceManager.GetString("FarmIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المزرعه غير موجود.
        /// </summary>
        public static string FarmIdNotFound {
            get {
                return ResourceManager.GetString("FarmIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmID is Invalid.
        /// </summary>
        public static string FarmNotFound {
            get {
                return ResourceManager.GetString("FarmNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017.
        /// </summary>
        public static string FarmPropertyType {
            get {
                return ResourceManager.GetString("FarmPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.
        /// </summary>
        public static string FarmRequestTypeNotValid {
            get {
                return ResourceManager.GetString("FarmRequestTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3022.
        /// </summary>
        public static string FarmRequestTypeOrchards {
            get {
                return ResourceManager.GetString("FarmRequestTypeOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2051.
        /// </summary>
        public static string FarmRequestTypeOrchardsnotvalid {
            get {
                return ResourceManager.GetString("FarmRequestTypeOrchardsnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmRequestTypeOrchards is required.
        /// </summary>
        public static string FarmRequestTypeOrchardsRequired {
            get {
                return ResourceManager.GetString("FarmRequestTypeOrchardsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmRequest Type is Required.
        /// </summary>
        public static string FarmRequestTypeRequired {
            get {
                return ResourceManager.GetString("FarmRequestTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        public static string FarmsAreaNumberOnly {
            get {
                return ResourceManager.GetString("FarmsAreaNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2093.
        /// </summary>
        public static string FarmShareOrchardsNotValid {
            get {
                return ResourceManager.GetString("FarmShareOrchardsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الرقم القومى ليس لديه اى مزراع.
        /// </summary>
        public static string FarmsInfoNotFound {
            get {
                return ResourceManager.GetString("FarmsInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentCode is Invalid.
        /// </summary>
        public static string FileCodeNotExist {
            get {
                return ResourceManager.GetString("FileCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saving Error.
        /// </summary>
        public static string FileSavingError {
            get {
                return ResourceManager.GetString("FileSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachement is Invalid, Maximum size is 2 Mega.
        /// </summary>
        public static string FilLenghtMessage {
            get {
                return ResourceManager.GetString("FilLenghtMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilLenghtNotValid.
        /// </summary>
        public static string FilLenghtNotValid {
            get {
                return ResourceManager.GetString("FilLenghtNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المزرعه غير موجوده.
        /// </summary>
        public static string FrmNotFound {
            get {
                return ResourceManager.GetString("FrmNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2045.
        /// </summary>
        public static string FullNameShipmment {
            get {
                return ResourceManager.GetString("FullNameShipmment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-01.
        /// </summary>
        public static string GetFarmSlug {
            get {
                return ResourceManager.GetString("GetFarmSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Governorate is Invalid.
        /// </summary>
        public static string GovernorateCodeNotExist {
            get {
                return ResourceManager.GetString("GovernorateCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2063.
        /// </summary>
        public static string GovernorateCodeNotValid {
            get {
                return ResourceManager.GetString("GovernorateCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2048.
        /// </summary>
        public static string GovernorateCodeShipmment {
            get {
                return ResourceManager.GetString("GovernorateCodeShipmment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2048.
        /// </summary>
        public static string GovernorateNotExist {
            get {
                return ResourceManager.GetString("GovernorateNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmGovernorateOrchards is Invalid.
        /// </summary>
        public static string GovernorateOrchaCodeNotExist {
            get {
                return ResourceManager.GetString("GovernorateOrchaCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2028.
        /// </summary>
        public static string GovernorateOrchards {
            get {
                return ResourceManager.GetString("GovernorateOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GovernorateCode  is Invalid.
        /// </summary>
        public static string GovernorateShipMmentCodeNotExist {
            get {
                return ResourceManager.GetString("GovernorateShipMmentCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3029.
        /// </summary>
        public static string GreenHouseNumberInvalid {
            get {
                return ResourceManager.GetString("GreenHouseNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenHouseNumber is required.
        /// </summary>
        public static string GreenHouseNumberRequired {
            get {
                return ResourceManager.GetString("GreenHouseNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Or not Valid Type.
        /// </summary>
        public static string HeaderValidtion {
            get {
                return ResourceManager.GetString("HeaderValidtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2059.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character is Invalid.
        /// </summary>
        public static string InvalidCharacterOrcha {
            get {
                return ResourceManager.GetString("InvalidCharacterOrcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequesterType is invalid.
        /// </summary>
        public static string InvalidRequesterType {
            get {
                return ResourceManager.GetString("InvalidRequesterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsConfirmed is Invalid.
        /// </summary>
        public static string IsConfirmedNotValid {
            get {
                return ResourceManager.GetString("IsConfirmedNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Or Password not valid.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-01 is the default value , it should only work with these service slug.
        /// </summary>
        public static string LooKupSlugNotApplied {
            get {
                return ResourceManager.GetString("LooKupSlugNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-02.
        /// </summary>
        public static string MALR_02 {
            get {
                return ResourceManager.GetString("MALR-02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-03.
        /// </summary>
        public static string MALR_03 {
            get {
                return ResourceManager.GetString("MALR-03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-06.
        /// </summary>
        public static string MALR_06 {
            get {
                return ResourceManager.GetString("MALR-06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-11.
        /// </summary>
        public static string MALR_11 {
            get {
                return ResourceManager.GetString("MALR-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-17.
        /// </summary>
        public static string MALR_17 {
            get {
                return ResourceManager.GetString("MALR-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALR-22.
        /// </summary>
        public static string MALR_22 {
            get {
                return ResourceManager.GetString("MALR-22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizingMechanism is Invalid.
        /// </summary>
        public static string MechanismNotValid {
            get {
                return ResourceManager.GetString("MechanismNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2001.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2002.
        /// </summary>
        public static string NationalIdLenght {
            get {
                return ResourceManager.GetString("NationalIdLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalId is invalid.
        /// </summary>
        public static string NationalIdNotFound {
            get {
                return ResourceManager.GetString("NationalIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2025.
        /// </summary>
        public static string NorthernBorderOrchards {
            get {
                return ResourceManager.GetString("NorthernBorderOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M@LR@2o22.
        /// </summary>
        public static string Notification_Password_Prod_Malr {
            get {
                return ResourceManager.GetString("Notification_Password_Prod_Malr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://10.229.1.3/GGProxy/api/submission/submitgovtalk.
        /// </summary>
        public static string Notification_Url_Host_Production {
            get {
                return ResourceManager.GetString("Notification_Url_Host_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://10.229.1.3/proxy/api/submission/login.
        /// </summary>
        public static string Notification_Url_Prod_Malr {
            get {
                return ResourceManager.GetString("Notification_Url_Prod_Malr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prod_Malr.
        /// </summary>
        public static string Notification_UserName_Prod_Malr {
            get {
                return ResourceManager.GetString("Notification_UserName_Prod_Malr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K5*S_wEZr*eG9m8}.
        /// </summary>
        public static string NotificationPassword {
            get {
                return ResourceManager.GetString("NotificationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage_Malr2.
        /// </summary>
        public static string NotificationUserName {
            get {
                return ResourceManager.GetString("NotificationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2343434.
        /// </summary>
        public static string numberOnly {
            get {
                return ResourceManager.GetString("numberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارقام فقط من 0 الى 1.
        /// </summary>
        public static string numberRange {
            get {
                return ResourceManager.GetString("numberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to originatingChannel is Invalid.
        /// </summary>
        public static string originatingChannelNotValid {
            get {
                return ResourceManager.GetString("originatingChannelNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2037.
        /// </summary>
        public static string originatingRequired {
            get {
                return ResourceManager.GetString("originatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to originatingUserType is Invalid.
        /// </summary>
        public static string originatingUserTypeNotValid {
            get {
                return ResourceManager.GetString("originatingUserTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2009.
        /// </summary>
        public static string OwnerNameRequired {
            get {
                return ResourceManager.GetString("OwnerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2096.
        /// </summary>
        public static string PaymentRequestNumberNotvalid {
            get {
                return ResourceManager.GetString("PaymentRequestNumberNotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2053.
        /// </summary>
        public static string PaymentRequestTotalAmount {
            get {
                return ResourceManager.GetString("PaymentRequestTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2056.
        /// </summary>
        public static string PaymentRequestTotalNotValid {
            get {
                return ResourceManager.GetString("PaymentRequestTotalNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006.
        /// </summary>
        public static string PhoneLenght {
            get {
                return ResourceManager.GetString("PhoneLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2005.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2046.
        /// </summary>
        public static string PhoneNumberShipmment {
            get {
                return ResourceManager.GetString("PhoneNumberShipmment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://10.35.45.36/proxy/api/submission/login.
        /// </summary>
        public static string PortlaLoginHost {
            get {
                return ResourceManager.GetString("PortlaLoginHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://10.35.45.36/GGProxy/api/submission/submitgovtalk.
        /// </summary>
        public static string PortlaNotificationUrl {
            get {
                return ResourceManager.GetString("PortlaNotificationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K5*S_wEZr*eG9m7}.
        /// </summary>
        public static string PortlaPassword {
            get {
                return ResourceManager.GetString("PortlaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage_Malr.
        /// </summary>
        public static string PortlaUserName {
            get {
                return ResourceManager.GetString("PortlaUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020.
        /// </summary>
        public static string PropertyTypeFarms {
            get {
                return ResourceManager.GetString("PropertyTypeFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmPropertyType is invalid.
        /// </summary>
        public static string PropertyTypeNotValid {
            get {
                return ResourceManager.GetString("PropertyTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmPropertyTypeOrchards is invalid.
        /// </summary>
        public static string PropertyTypeNotValidOrcha {
            get {
                return ResourceManager.GetString("PropertyTypeNotValidOrcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2032.
        /// </summary>
        public static string PropertyTypeNumberOnly {
            get {
                return ResourceManager.GetString("PropertyTypeNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2031.
        /// </summary>
        public static string PropertyTypeOrchards {
            get {
                return ResourceManager.GetString("PropertyTypeOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3025.
        /// </summary>
        public static string ReconciliationDateNotValid {
            get {
                return ResourceManager.GetString("ReconciliationDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2075.
        /// </summary>
        public static string RequestIDNotValid {
            get {
                return ResourceManager.GetString("RequestIDNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2039.
        /// </summary>
        public static string RequestIDRequired {
            get {
                return ResourceManager.GetString("RequestIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request has no paid.
        /// </summary>
        public static string RequestNotPaid {
            get {
                return ResourceManager.GetString("RequestNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestId  is Invalid.
        /// </summary>
        public static string RequestNotValid {
            get {
                return ResourceManager.GetString("RequestNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fees not found for this request.
        /// </summary>
        public static string RequestNotValidFees {
            get {
                return ResourceManager.GetString("RequestNotValidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2075.
        /// </summary>
        public static string RequestNotValidRequired {
            get {
                return ResourceManager.GetString("RequestNotValidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2083.
        /// </summary>
        public static string RequestNumberInvalid {
            get {
                return ResourceManager.GetString("RequestNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2082.
        /// </summary>
        public static string RequestNumberRequired {
            get {
                return ResourceManager.GetString("RequestNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3018.
        /// </summary>
        public static string RequestPartyEmailNotValid {
            get {
                return ResourceManager.GetString("RequestPartyEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010.
        /// </summary>
        public static string RequestPartyNameValidation {
            get {
                return ResourceManager.GetString("RequestPartyNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المرفقات مطلوبه.
        /// </summary>
        public static string RequestRequireAttachments {
            get {
                return ResourceManager.GetString("RequestRequireAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المزرعه مطلوبه.
        /// </summary>
        public static string RequestRequiremenInfo {
            get {
                return ResourceManager.GetString("RequestRequiremenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request status not valid should be documentsRequired ,.
        /// </summary>
        public static string RequestStatusComplainNotValid {
            get {
                return ResourceManager.GetString("RequestStatusComplainNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Request Status is Invalid.
        /// </summary>
        public static string RequestStatusNotValid {
            get {
                return ResourceManager.GetString("RequestStatusNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmRequestType is invalid.
        /// </summary>
        public static string RequestTypeNotValid {
            get {
                return ResourceManager.GetString("RequestTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmRequestTypeOrchards is Invalid.
        /// </summary>
        public static string RequestTypeNotValidOrcha {
            get {
                return ResourceManager.GetString("RequestTypeNotValidOrcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.
        /// </summary>
        public static string RequestTypeNumberOnly {
            get {
                return ResourceManager.GetString("RequestTypeNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المرفقات  وبيانات المزرعه مطلوبه.
        /// </summary>
        public static string RequireAttachmentsAndInfo {
            get {
                return ResourceManager.GetString("RequireAttachmentsAndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequsterType Required.
        /// </summary>
        public static string RequsterTypeNotValid {
            get {
                return ResourceManager.GetString("RequsterTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequsterType is required.
        /// </summary>
        public static string RequsterTypeRequired {
            get {
                return ResourceManager.GetString("RequsterTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SavedSuccess {
            get {
                return ResourceManager.GetString("SavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2095.
        /// </summary>
        public static string SenderRequestNumberNotValid {
            get {
                return ResourceManager.GetString("SenderRequestNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceCode is Invalid.
        /// </summary>
        public static string ServiceCodeErrror {
            get {
                return ResourceManager.GetString("ServiceCodeErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2074.
        /// </summary>
        public static string ServiceCodeInvalid {
            get {
                return ResourceManager.GetString("ServiceCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2003.
        /// </summary>
        public static string serviceCodeRequired {
            get {
                return ResourceManager.GetString("serviceCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service  slug not related with service code.
        /// </summary>
        public static string ServiceCodeSlugErrror {
            get {
                return ResourceManager.GetString("ServiceCodeSlugErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceEntityId is Invalid.
        /// </summary>
        public static string serviceEntityIdNotValid {
            get {
                return ResourceManager.GetString("serviceEntityIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is Invalid.
        /// </summary>
        public static string servicelookupValuesnotfound {
            get {
                return ResourceManager.GetString("servicelookupValuesnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2038.
        /// </summary>
        public static string ServiceSlugRequired {
            get {
                return ResourceManager.GetString("ServiceSlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3019.
        /// </summary>
        public static string ShipmenPhoneNumber {
            get {
                return ResourceManager.GetString("ShipmenPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3020.
        /// </summary>
        public static string ShipmenPhoneNumberPhoneLenght {
            get {
                return ResourceManager.GetString("ShipmenPhoneNumberPhoneLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is Invalid.
        /// </summary>
        public static string ShipmentCodeNotFound {
            get {
                return ResourceManager.GetString("ShipmentCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Info required.
        /// </summary>
        public static string ShipmentInfoNotFound {
            get {
                return ResourceManager.GetString("ShipmentInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this request has no have any shipment informations .
        /// </summary>
        public static string ShipmentNumberNotFoundForThisRequest {
            get {
                return ResourceManager.GetString("ShipmentNumberNotFoundForThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2040.
        /// </summary>
        public static string ShipmentNumberRequired {
            get {
                return ResourceManager.GetString("ShipmentNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات التوصيل غير موجوده.
        /// </summary>
        public static string ShipmmentAdressNotFond {
            get {
                return ResourceManager.GetString("ShipmmentAdressNotFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Slug is invalid.
        /// </summary>
        public static string SlugNotFound {
            get {
                return ResourceManager.GetString("SlugNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2027.
        /// </summary>
        public static string SouthernBorderOrchards {
            get {
                return ResourceManager.GetString("SouthernBorderOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2085.
        /// </summary>
        public static string StatusNotValid {
            get {
                return ResourceManager.GetString("StatusNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2070.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  StParentCode is Invalid.
        /// </summary>
        public static string StParentCode {
            get {
                return ResourceManager.GetString("StParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2094.
        /// </summary>
        public static string StParentCodeNotValid {
            get {
                return ResourceManager.GetString("StParentCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes Login.
        /// </summary>
        public static string SuccesLogin {
            get {
                return ResourceManager.GetString("SuccesLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الارسال بنجاح.
        /// </summary>
        public static string SuccessSend {
            get {
                return ResourceManager.GetString("SuccessSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2071.
        /// </summary>
        public static string TimeStampNotValid {
            get {
                return ResourceManager.GetString("TimeStampNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2069.
        /// </summary>
        public static string TimeStampRequired {
            get {
                return ResourceManager.GetString("TimeStampRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2073.
        /// </summary>
        public static string TransactionNumberNotValid {
            get {
                return ResourceManager.GetString("TransactionNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2055.
        /// </summary>
        public static string TransactionNumberRequired {
            get {
                return ResourceManager.GetString("TransactionNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2034.
        /// </summary>
        public static string TypeOfDamageIsRequired {
            get {
                return ResourceManager.GetString("TypeOfDamageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this user doesn&apos;t have any farms.
        /// </summary>
        public static string userdoesnthaveanyfarms {
            get {
                return ResourceManager.GetString("userdoesnthaveanyfarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المزرعه ليست مرتبطه بهذا الطلب.
        /// </summary>
        public static string UserFarmNotFound {
            get {
                return ResourceManager.GetString("UserFarmNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string ValidtionErrorMessage {
            get {
                return ResourceManager.GetString("ValidtionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2026.
        /// </summary>
        public static string WesternBorderOrchards {
            get {
                return ResourceManager.GetString("WesternBorderOrchards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2087.
        /// </summary>
        public static string YearnotValid {
            get {
                return ResourceManager.GetString("YearnotValid", resourceCulture);
            }
        }
    }
}
